1 st

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -13,12 +13,11 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v3
 
+      - name: Debug files
+        run: ls -la .github/workflows/ && cat .github/workflows/inventory.ini || echo "inventory.ini not found"
+
       - name: Configure Kubeconfig
         run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig
-
-        - name: Debug files
-         run: ls -la .github/workflows/ && cat .github/workflows/inventory.ini || echo "inventory.ini not found"
-
 
       - name: Run Ansible Playbook to Deploy ArgoCD
         env:
@@ -31,4 +30,3 @@ jobs:
       - name: Retrieve ArgoCD admin password
         run: |
           echo "ArgoCD Admin Password: $(kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath='{.data.password}' | base64 --decode)" -vv
-
