1 st

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -16,6 +16,10 @@ jobs:
       - name: Configure Kubeconfig
         run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig
 
+        - name: Debug files
+         run: ls -la .github/workflows/ && cat .github/workflows/inventory.ini || echo "inventory.ini not found"
+
+
       - name: Run Ansible Playbook to Deploy ArgoCD
         env:
           KUBECONFIG: kubeconfig
