1 st

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -14,7 +14,7 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Debug files
-        run: ls -la .github/workflows/ && cat .github/workflows/inventory.ini || echo "inventory.ini not found"
+        run: ls -la .github/workflows/ && cat .github/workflows/inventory.ini || echo "inventory.ini not found" -vv
 
       - name: Configure Kubeconfig
         run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig
